### ISSUE TITLE
Figure this out (ObjectDisposedException)

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/FleetManager#104]
```
2021-04-16 19:41:42.972 +02:00|FTL||||Could not start
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at LiteDB.Async.LiteDatabaseAsync.Dispose(Boolean disposing)
   at LiteDB.Async.LiteDatabaseAsync.Dispose()
   at FleetManager.Model.Tech.LiteDb.LiteDbProjection`1.Dispose() in C:\projects-rebusfm\fm7-server\FleetManager.Model.Tech\LiteDb\LiteDbProjection.cs:line 171
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
   at FleetManager.WebApp.Helpers.Init.AsyncInitializationExtensions.AsyncInitHostDecorator.Dispose() in C:\projects-rebusfm\fm7-server\FleetManager.WebApp\Helpers\Init\AsyncInitializationExtensions.cs:line 97
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at FleetManager.WebApp.Program.Main(String[] args) in C:\projects-rebusfm\fm7-server\FleetManager.WebApp\Program.cs:line 96
```

**Comment by PrasannaGrandhi** [comment]
Hi, do you have any update on this issue ?

**Comment by mookid8000** [comment]
Not readily, no. Is it something you've experienced?

**Comment by PrasannaGrandhi** [comment]
Yeah. We are getting, and really waiting for it to be solved !!! do you some alternatives to exclude this error or any guesses why its coming ?

**Comment by mookid8000** [comment]
Which version of Fleet Manager are you using? Could you give me the full exception details from your log?

**Comment by PrasannaGrandhi** [comment]
not sure about version, but we downloaded from here [InstallerLink](https://github.com/rebus-org/FleetManager/tree/master/installers) and installed locally after that deployed those exe dlls to azure cloud as a app service.
Here is the log

`2021-04-14 06:31:47.978 +00:00|INF|||FleetManager.Model.Tech.Topos.EventStatsCollector|Event processing stats { Ok: [{ Type: "events/all/pool0", Count: 5, AvgMs: 3.70846, SumMs: 18.5423 }], Err: [], N: 1 }
2021-04-14 06:31:48.054 +00:00|FTL||||Could not start
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at LiteDB.Async.LiteDatabaseAsync.Dispose(Boolean disposing)
   at LiteDB.Async.LiteDatabaseAsync.Dispose()
   at FleetManager.Model.Tech.LiteDb.LiteDbProjection`1.Dispose() in C:\projects-rebusfm\fm7-server\FleetManager.Model.Tech\LiteDb\LiteDbProjection.cs:line 171
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
   at FleetManager.WebApp.Helpers.Init.AsyncInitializationExtensions.AsyncInitHostDecorator.Dispose() in C:\projects-rebusfm\fm7-server\FleetManager.WebApp\Helpers\Init\AsyncInitializationExtensions.cs:line 96
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at FleetManager.WebApp.Program.Main(String[] args) in C:\projects-rebusfm\fm7-server\FleetManager.WebApp\Program.cs:line 94
2021-04-14 06:31:53.110 +00:00|INF|||Microsoft.Hosting.Lifetime|Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.
2021-04-14 06:31:55.932 +00:00|INF|||FleetManager.Model.Services.EventMarkerQueue|Cleaned up 5 event markers, queue contains 0 markers now
`

**Comment by mookid8000** [comment]
The logs seem to date back to April – could you try and update to the newest version of Fleet Manager and then see if the issue is still there?

**Comment by PrasannaGrandhi** [comment]
Where can I get newest version, can you please post the link please..

**Comment by PrasannaGrandhi** [comment]
Should I need to run `fm-installer update ` command !!?

**Comment by mookid8000** [comment]
Yes 🙂 it's
```dos
> set fmpath=<path-to-where-your-fleetmanager-is-installed>
```
and then you
```dos
> fm-installer update
```
to update it.

**Comment by PrasannaGrandhi** [comment]
Updated with latest.
But just one thing, we installed fleetmanager as app service, taking installation deployed from on prem. Hope that should not be reason for the above error.

**Comment by PrasannaGrandhi** [comment]
still facing the same issue.. any other suggestions pls..

**Comment by PrasannaGrandhi** [comment]
Its working now after changing some internal config setting.

**Comment by mookid8000** [comment]
Hi @PrasannaGrandhi !

 I've released version 4.9.3 of Fleet Manager, which should fix the exception above.

It also fixed the filtering on the Actitvity Overview.

Let me know if it works out for you 🙂

**Comment by PrasannaGrandhi** [comment]
Yeah, just updated with latest 4.9.3 and its perfectly working fine. Thanks 👍

**Comment by mookid8000** [comment]
Good to hear 🙂

**Comment by PrasannaGrandhi** [comment]
Just one more thing, wanted to ask, can we add custom endpoints to Fleet Manager though some configuration file ?

**Comment by mookid8000** [comment]
Are you thinking about opening additional ports, or simply about customizing which port it's listening on?

**Comment by PrasannaGrandhi** [comment]
We wanted to add an endpoint(_basically to access a txt file from FleetManager installed path_), so that we can check the health of the app service and can successfully route to gateway..!!

Is that possible to configure an endpoint from any setting files ?

**Comment by mookid8000** [comment]
If you place a file with one of the extensions js, svg, png, ttf, woff2, eot, map, ico, or html in the client subdirectory of Fleet Manager's installation directory, then that file will be served as static content... would that work in your case?

**Comment by PrasannaGrandhi** [comment]
Exactly what I'm expecting.. it worked.. thanks :) :) Good day.

**Comment by mookid8000** [comment]
Happy to hear that 🙂 good day to you too
